# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 6
language: 'en-us'

# Website info
name:
description:

short_url: 'df3ndr.io'
google_analytics: G-QH118866XT
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ""
url: "http://df3ndr.io"

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html

# permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
